### ISSUE TITLE
The Library adds endpoint that doesn't exist. 

### ISSUE THREAD

**Issue by ancgate** [Tiberriver256/Swashbuckle.AspNetCore.Community.OData#121]
### Describe the feature

I have created only one get endpoint but when I run swagger it gives me all http verbs. Can we only show the endpoint that was defined in the controller?

**Comment by Tiberriver256** [comment]
This library is designed to create the swagger of your EdmModel, not reverse engineer from your controllers.

So if you're showing all http verbs your EdmModel may be configured to say that you support all http verbs and correcting that would correct your swagger document.

The design is a bit more time-consuming but encourages developers to make correct EdmModels which will make a correct `/$metadata` document for your API consumers who may be using an OData client instead of a swagger client.

For example, if you only wanted to support the two GET requests for an entity set, you'd add delete, update and insert restrictions to your edm model:

```csharp
builder.EntityType<WeatherForecast>().HasKey(f => f.Id);
builder
    .EntityType<WeatherForecast>()
    .HasDeleteRestrictions()
    .IsDeletable(false)
    .HasDescription("Not supported");
builder
    .EntityType<WeatherForecast>()
    .HasUpdateRestrictions()
    .IsUpdatable(false)
    .HasDescription("Not supported");
builder
    .EntityType<WeatherForecast>()
    .HasInsertRestrictions()
    .IsInsertable(false)
    .HasDescription("Not supported");

builder.EntitySet<WeatherForecast>("WeatherForecasts");
```

With those restrictions added to your EdmModel your swagger doc would now only show the two GET endpoints and no longer show the DELETE/PUT/POST/etc. endpoints.
